services:
  attacker:
    build: ./attacker
    container_name: arp-attacker
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      lab:
        ipv4_address: 10.10.0.10
        mac_address: 00:00:00:00:00:10
    command: ["sleep", "infinity"]

  victim:
    build: ./victim
    container_name: arp-victim
    cap_add:
      - NET_ADMIN
    networks:
      lab:
        ipv4_address: 10.10.0.20
        mac_address: 00:00:00:00:00:20
 
  server:
    build: ./server
    container_name: arp-flag-server
    networks:
      lab:
        ipv4_address: 10.10.0.30
        mac_address: 00:00:00:00:00:30


networks:
  lab:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24